### ISSUE TITLE
thenThrow cannot be used with a Throwable when using PHP 7 and up

### ISSUE THREAD

**Issue by VincentBLortie** [mlively/Phake#256] opened 2018-01-17 15:24 UTC
When using the thenThrow answer, it is only possible to throw objects which extend the \Exception base class.

Since PHP 7, the \Throwable interface is the base interface for any object that can be thrown. It would make sense for thenThrow to accept objects which implement \Throwable, even if they do not extend \Exception.

A workaround is to use thenReturnCallback, where the Throwable is thrown in the callback.

**Comment by adoy** [comment] 2021-03-20 17:28
Thanks for Opening this issue Vincent :-)

I know it was a long ago but the issue is now fixed and it will be available in the next release (4.0.0)

**Closed** 2021-03-20 17:34 UTC
Labels: Enhancement
